'use client';
import { useEffect, useState, useRef, FormEvent } from 'react';
import { AnimatePresence, motion, useInView } from 'framer-motion';
import { ArrowDownRight, ArrowRight, ArrowUpRight, Check, ChevronLeft, ChevronRight, Code2, Github, Globe2, Layers3, Linkedin, Menu, Moon, MousePointer2, Send, Sparkles, Sun, X } from 'lucide-react';
import { experience, profile, projects, skillGroups, testimonials } from '@/lib/data';

const rise = { hidden:{opacity:0,y:24}, visible:{opacity:1,y:0,transition:{duration:.65,ease:[.22,1,.36,1] as const}} };
function Reveal({children, className=''}:{children:React.ReactNode;className?:string}) { const ref=useRef(null); const visible=useInView(ref,{once:true,margin:'-70px'}); return <motion.div ref={ref} className={className} variants={rise} initial="hidden" animate={visible?'visible':'hidden'}>{children}</motion.div>; }
function Magnetic({children,className='',href}:{children:React.ReactNode;className?:string;href?:string}) { const [offset,setOffset]=useState({x:0,y:0}); const ref=useRef<HTMLElement>(null); const move=(e:React.MouseEvent)=>{if(!ref.current)return;const r=ref.current.getBoundingClientRect();setOffset({x:(e.clientX-r.left-r.width/2)*.12,y:(e.clientY-r.top-r.height/2)*.12});}; const reset=()=>setOffset({x:0,y:0}); const style={transform:`translate(${offset.x}px, ${offset.y}px)`}; return href?<a ref={ref as React.RefObject<HTMLAnchorElement>} href={href} onMouseMove={move} onMouseLeave={reset} className={className} style={style}>{children}</a>:<button ref={ref as React.RefObject<HTMLButtonElement>} onMouseMove={move} onMouseLeave={reset} className={className} style={style}>{children}</button>; }
export default function Home(){
 const [theme,setTheme]=useState<'dark'|'light'>('dark'); const [filter,setFilter]=useState('All'); const [testimonial,setTestimonial]=useState(0); const [mobileOpen,setMobileOpen]=useState(false); const [cursor,setCursor]=useState({x:-30,y:-30}); const [form,setForm]=useState({name:'',email:'',message:''}); const [status,setStatus]=useState<'idle'|'sending'|'success'|'error'>('idle'); const [errors,setErrors]=useState<Record<string,string>>({});
 useEffect(()=>{const saved=localStorage.getItem('portfolio-theme') as 'dark'|'light'|null; if(saved)setTheme(saved); const move=(e:MouseEvent)=>setCursor({x:e.clientX,y:e.clientY}); window.addEventListener('mousemove',move); return()=>window.removeEventListener('mousemove',move);},[]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('portfolio-theme',theme);},[theme]);
 useEffect(()=>{const t=window.setInterval(()=>setTestimonial(v=>(v+1)%testimonials.length),6500);return()=>window.clearInterval(t);},[]);
 const categories=['All','Full-Stack','Frontend','Mobile','AI']; const shown=filter==='All'?projects:projects.filter(p=>p.category===filter);
 const validate=()=>{const next:Record<string,string>={};if(!form.name.trim())next.name='Please enter your name.';if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email))next.email='Enter a valid email address.';if(form.message.trim().length<12)next.message='Add a little more detail (12 characters minimum).';setErrors(next);return Object.keys(next).length===0;};
 async function submit(e:FormEvent){e.preventDefault();if(!validate())return;setStatus('sending');try{const endpoint=process.env.NEXT_PUBLIC_FORMSPREE_ENDPOINT;if(endpoint){const res=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify(form)});if(!res.ok)throw new Error('Form submission failed');}else{await new Promise(r=>setTimeout(r,850));}setStatus('success');setForm({name:'',email:'',message:''});}catch{setStatus('error');}}
 const current=testimonials[testimonial];
 return <main>
  <div className="cursor-dot" style={{transform:`translate(${cursor.x-4}px,${cursor.y-4}px)`}} aria-hidden="true" />
  <header className="fixed top-0 z-50 w-full border-b backdrop-blur-xl" style={{borderColor:'var(--line)',background:'color-mix(in srgb, var(--bg) 82%, transparent)'}}><div className="wrap flex h-[76px] items-center justify-between gap-6">
   <a href="#home" className="flex items-center gap-3" aria-label="Alex Morgan home"><span className="flex h-9 w-9 items-center justify-center rounded-xl text-sm font-black" style={{background:'var(--accent)',color:'#11140b'}}>a.</span><span className="text-sm font-bold tracking-tight">alexmorgan<span style={{color:'var(--muted)'}}>.dev</span></span></a>
   <nav className="hidden items-center gap-7 lg:flex" aria-label="Main navigation">{[['About','#about'],['Work','#work'],['Experience','#experience'],['Kind words','#testimonials']].map(([label,href])=><a className="nav-link" href={href} key={label}>{label}</a>)}</nav>
   <div className="flex items-center gap-3"><button onClick={()=>setTheme(theme==='dark'?'light':'dark')} className="surface flex h-10 w-10 items-center justify-center rounded-full" aria-label={`Switch to ${theme==='dark'?'light':'dark'} mode`}>{theme==='dark'?<Sun size={16}/>:<Moon size={16}/>}</button><a href="#contact" className="btn btn-primary hidden sm:inline-flex">Let’s talk <ArrowUpRight size={15}/></a><button className="surface flex h-10 w-10 items-center justify-center rounded-full lg:hidden" onClick={()=>setMobileOpen(!mobileOpen)} aria-label="Toggle menu">{mobileOpen?<X size={17}/>:<Menu size={17}/>}</button></div>
  </div>{mobileOpen&&<nav className="wrap flex flex-col gap-5 pb-6 lg:hidden">{[['About','#about'],['Work','#work'],['Experience','#experience'],['Kind words','#testimonials'],['Contact','#contact']].map(([label,href])=><a key={label} href={href} onClick={()=>setMobileOpen(false)} className="nav-link">{label}</a>)}</nav>}</header>
  <section id="home" className="relative flex min-h-[850px] items-center overflow-hidden pb-20 pt-32"><div className="grid-lines absolute inset-0 opacity-60"/><div className="pointer-events-none absolute -right-36 top-32 h-[540px] w-[540px] rounded-full opacity-20 blur-[110px]" style={{background:'var(--accent)'}}/><div className="wrap relative grid items-center gap-14 lg:grid-cols-[1.1fr_.9fr]">
   <div><motion.div initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} transition={{duration:.7}} className="mb-8 flex items-center gap-3"><span className="relative flex h-2.5 w-2.5"><span className="absolute inline-flex h-full w-full animate-ping rounded-full opacity-70" style={{background:'var(--accent)'}}/><span className="relative inline-flex h-2.5 w-2.5 rounded-full" style={{background:'var(--accent)'}}/></span><span className="eyebrow">Available for select projects</span></motion.div>
    <motion.p initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.1}} className="mb-4 text-sm" style={{color:'var(--muted)'}}>Hey there, I’m Alex Morgan</motion.p><motion.h1 initial={{opacity:0,y:28}} animate={{opacity:1,y:0}} transition={{duration:.8,delay:.12}} className="max-w-[760px] text-[clamp(4rem,8.7vw,7.8rem)] font-black leading-[.86] tracking-[-.09em]">Digital craft.<br/><span style={{color:'var(--accent)'}}>Human</span> impact.</motion.h1>
    <motion.p initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} transition={{delay:.3}} className="mt-8 max-w-[510px] text-base leading-7 sm:text-lg" style={{color:'var(--muted)'}}>I’m a creative developer building thoughtful products, expressive interfaces, and digital experiences that just feel right.</motion.p>
    <motion.div initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{delay:.4}} className="mt-9 flex flex-wrap gap-3"><Magnetic href="#work" className="btn btn-primary">Explore my work <ArrowDownRight size={16}/></Magnetic><Magnetic href="#contact" className="btn btn-secondary">Start a conversation <ArrowUpRight size={15}/></Magnetic></motion.div>
    <div className="mt-12 flex items-center gap-5"><a href={profile.github} target="_blank" rel="noreferrer" aria-label="GitHub" className="muted transition hover:opacity-70"><Github size={18}/></a><a href={profile.linkedin} target="_blank" rel="noreferrer" aria-label="LinkedIn" className="muted transition hover:opacity-70"><Linkedin size={18}/></a><span className="h-px w-12" style={{background:'var(--line)'}}/><span className="text-xs" style={{color:'var(--muted)'}}>London, UK · 51°30′N</span></div>
   </div>
   <motion.div initial={{opacity:0,scale:.92,rotate:2}} animate={{opacity:1,scale:1,rotate:0}} transition={{duration:.9,delay:.25}} className="relative mx-auto w-full max-w-[460px]"><div className="absolute -inset-5 rounded-[40px] border" style={{borderColor:'var(--line)',transform:'rotate(-5deg)'}}/><div className="relative aspect-[.9] overflow-hidden rounded-[32px] border p-5" style={{borderColor:'var(--line)',background:'linear-gradient(145deg, var(--panel), color-mix(in srgb, var(--accent) 8%, var(--panel))'}}><div className="flex items-center justify-between"><span className="eyebrow">Developer / Designer</span><Sparkles size={17} style={{color:'var(--accent)'}}/></div><div className="absolute inset-x-5 bottom-5 top-16 overflow-hidden rounded-[24px]" style={{background:'radial-gradient(circle at 50% 35%, #d8e2ce 0%, #87958c 25%, #343c3c 56%, #171a20 100%)'}}><div className="absolute left-1/2 top-[16%] h-[32%] w-[34%] -translate-x-1/2 rounded-[48%_48%_43%_43%]" style={{background:'linear-gradient(135deg,#d7ad8b,#956c55)',boxShadow:'inset 0 10px 0 #25262b'}}/><div className="absolute left-1/2 top-[46%] h-[65%] w-[76%] -translate-x-1/2 rounded-t-[45%]" style={{background:'linear-gradient(135deg,#202831,#101318)'}}/><div className="absolute inset-x-0 bottom-0 h-1/3" style={{background:'linear-gradient(transparent,rgba(10,12,15,.8))'}}/><div className="absolute bottom-5 left-5 right-5 flex items-end justify-between"><div><p className="text-2xl font-bold tracking-tight text-white">Alex Morgan</p><p className="mt-1 text-xs text-white/65">Building the next useful thing.</p></div><span className="flex h-10 w-10 items-center justify-center rounded-full" style={{background:'var(--accent)',color:'#111'}}><Code2 size={19}/></span></div></div><div className="absolute -left-5 top-[30%] flex items-center gap-2 rounded-2xl border px-4 py-3 shadow-glow backdrop-blur-xl" style={{borderColor:'var(--line)',background:'var(--panel)'}}><span className="text-xl">✳</span><div><p className="text-xs font-bold">Pixel perfect</p><p className="text-[10px] muted">By design</p></div></div><div className="absolute -right-3 bottom-[26%] flex items-center gap-2 rounded-2xl border px-4 py-3 backdrop-blur-xl" style={{borderColor:'var(--line)',background:'var(--panel)'}}><span className="h-2 w-2 rounded-full" style={{background:'var(--accent)'}}/><span className="text-xs font-bold">Built with intent</span></div></div></motion.div>
  </div><div className="absolute bottom-7 left-1/2 hidden -translate-x-1/2 items-center gap-3 text-[10px] uppercase tracking-[.22em] md:flex" style={{color:'var(--muted)'}}>Scroll to explore <span className="h-10 w-px" style={{background:'var(--line)'}}/></div></section>
  <section className="border-y py-7" style={{borderColor:'var(--line)'}}><div className="wrap grid grid-cols-2 gap-6 sm:grid-cols-4"><div><p className="text-3xl font-bold tracking-tight">7<span style={{color:'var(--accent)'}}>+</span></p><p className="mt-1 text-xs muted">Years in the craft</p></div><div><p className="text-3xl font-bold tracking-tight">32<span style={{color:'var(--accent)'}}>+</span></p><p className="mt-1 text-xs muted">Projects shipped</p></div><div><p className="text-3xl font-bold tracking-tight">12</p><p className="mt-1 text-xs muted">Teams partnered with</p></div><div><p className="text-3xl font-bold tracking-tight">∞</p><p className="mt-1 text-xs muted">Things left to learn</p></div></div></section>
  <section id="about" className="section"><div className="wrap"><Reveal><p className="eyebrow">01 / A little about me</p><div className="mt-6 grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><h2 className="section-title">Curious by nature.<br/><span style={{color:'var(--muted)'}}>Intentional by design.</span></h2><div className="pt-2"><p className="max-w-[650px] text-xl leading-8">{profile.bio}</p><p className="mt-5 max-w-[620px] leading-7 muted">I believe great digital work lives at the intersection of clarity, character, and care. My process blends pragmatic engineering with a strong visual point of view — always in service of the people using what we make.</p><a href="#contact" className="mt-7 inline-flex items-center gap-2 text-sm font-bold" style={{color:'var(--accent)'}}>A bit more about working together <ArrowRight size={16}/></a></div></div></Reveal>
   <div className="mt-16 grid gap-4 md:grid-cols-3">{[{icon:<Code2 size={20}/>,title:'Thoughtful code',text:'Reliable, accessible foundations that make future changes easier.'},{icon:<Layers3 size={20}/>,title:'Product thinking',text:'Every detail has a job. Every interaction earns its place.'},{icon:<MousePointer2 size={20}/>,title:'A little delight',text:'Micro-interactions and motion that make interfaces feel alive.'}].map((item,i)=><Reveal key={item.title}><div className="surface h-full rounded-2xl p-6 transition hover:-translate-y-1" style={{transitionDuration:'.25s'}}><span className="mb-6 flex h-11 w-11 items-center justify-center rounded-xl" style={{background:'color-mix(in srgb, var(--accent) 13%, transparent)',color:'var(--accent)'}}>{item.icon}</span><h3 className="text-base font-bold">{item.title}</h3><p className="mt-2 text-sm leading-6 muted">{item.text}</p></div></Reveal>)}</div>
  </div></section>
  <section id="work" className="section" style={{background:'color-mix(in srgb, var(--panel) 55%, transparent)'}}><div className="wrap"><Reveal><div className="flex flex-col justify-between gap-7 md:flex-row md:items-end"><div><p className="eyebrow">02 / Selected work</p><h2 className="section-title">Things I’ve<br/>put into the world<span style={{color:'var(--accent)'}}>.</span></h2></div><p className="max-w-[330px] pb-2 text-sm leading-6 muted">A selection of digital products, experiments, and collaborations — built with curiosity and a healthy obsession for detail.</p></div></Reveal>
   <div className="my-9 flex flex-wrap gap-2" role="group" aria-label="Filter projects">{categories.map(c=><button key={c} onClick={()=>setFilter(c)} className="rounded-full border px-4 py-2.5 text-xs font-bold transition" style={{borderColor:filter===c?'var(--accent)':'var(--line)',background:filter===c?'var(--accent)':'transparent',color:filter===c?'#11140b':'var(--muted)'}}>{c}</button>)}</div>
   <motion.div layout className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{shown.map((p)=><motion.article layout key={p.id} initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} exit={{opacity:0,y:10}} transition={{duration:.35}} className="project-card group overflow-hidden rounded-2xl border" style={{borderColor:'var(--line)',background:'var(--bg)'}}><div className="relative m-3 flex aspect-[1.35] items-center justify-center overflow-hidden rounded-xl" style={{background:p.color}}><div className="project-image relative flex h-full w-full items-center justify-center"><div className="absolute inset-4 rounded-lg border border-black/10"/><div className="absolute inset-x-[13%] top-[16%] bottom-[13%] rounded-2xl border border-black/10 bg-white/35 shadow-2xl backdrop-blur-sm"/><span className="relative z-10 text-4xl font-black tracking-[-.08em] text-black/75 sm:text-5xl">{p.visual}</span><span className="absolute bottom-[19%] right-[18%] z-10 h-5 w-5 rounded-full bg-black/75"/></div><span className="absolute left-4 top-4 rounded-full border border-black/10 bg-white/70 px-3 py-1.5 text-[10px] font-bold uppercase tracking-widest text-black/70">{p.category}</span><a href={p.live} target="_blank" rel="noreferrer" aria-label={`Open ${p.title}`} className="absolute bottom-4 right-4 flex h-10 w-10 items-center justify-center rounded-full bg-black text-white transition group-hover:rotate-45"><ArrowUpRight size={17}/></a></div><div className="p-5 pt-3"><div className="flex items-start justify-between gap-3"><h3 className="text-lg font-bold tracking-tight">{p.title}</h3><span className="text-xs muted">{p.year}</span></div><p className="mt-2 min-h-[48px] text-sm leading-6 muted">{p.description}</p><div className="mt-5 flex flex-wrap gap-2">{p.tags.map(t=><span key={t} className="rounded-full border px-2.5 py-1 text-[10px]" style={{borderColor:'var(--line)',color:'var(--muted)'}}>{t}</span>)}</div><div className="mt-5 flex gap-4 border-t pt-4" style={{borderColor:'var(--line)'}}><a href={p.github} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-xs font-bold muted hover:opacity-70"><Github size={14}/> Source</a><a href={p.live} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-xs font-bold muted hover:opacity-70"><Globe2 size={14}/> Live preview <ArrowUpRight size={12}/></a></div></div></motion.article>)}</motion.div>
   <p className="mt-7 text-xs muted">Showing {shown.length} of {projects.length} projects · Filter to explore by discipline.</p>
  </div></section>
  <section id="skills" className="section"><div className="wrap"><Reveal><p className="eyebrow">03 / Tools of the trade</p><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><div><h2 className="section-title">A versatile<br/>toolkit<span style={{color:'var(--accent)'}}>.</span></h2><p className="max-w-sm leading-7 muted">I choose tools for the problem, not the trend. Here’s a snapshot of the technologies and practices I reach for most.</p><div className="mt-8 flex items-center gap-3 text-xs muted"><span className="flex h-9 w-9 items-center justify-center rounded-full border" style={{borderColor:'var(--line)'}}><Code2 size={15}/></span>Always learning, never collecting for the sake of it.</div></div><div className="grid gap-4 sm:grid-cols-3">{skillGroups.map((group)=><div key={group.title} className="surface rounded-2xl p-5"><h3 className="mb-6 text-sm font-bold">{group.title}</h3>{group.skills.map(([name,level])=><Skill key={name as string} name={name as string} level={level as number}/>)}</div>)}</div></div></Reveal></div></section>
  <section id="experience" className="section" style={{background:'color-mix(in srgb, var(--panel) 55%, transparent)'}}><div className="wrap"><Reveal><p className="eyebrow">04 / The journey so far</p><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><h2 className="section-title">The path<br/>that got me here<span style={{color:'var(--accent)'}}>.</span></h2><p className="max-w-sm leading-7 muted">A few chapters that shaped how I think, build, and collaborate.</p></div><div className="relative space-y-9 pl-8 before:absolute before:bottom-2 before:left-[5px] before:top-2 before:w-px" style={{'--tw-content':'','--timeline':'var(--line)'} as React.CSSProperties}><div className="timeline-line absolute bottom-2 left-[5px] top-2 w-px"/>{experience.map((e,i)=><Reveal key={e.role}><div className="relative"><span className="absolute -left-[32px] top-1 h-[11px] w-[11px] rounded-full border-2" style={{background:'var(--bg)',borderColor:i===0?'var(--accent)':'var(--muted)'}}/><p className="eyebrow">{e.date}</p><h3 className="mt-2 text-xl font-bold tracking-tight">{e.role}</h3><p className="mt-1 text-sm" style={{color:'var(--accent)'}}>{e.company}</p><p className="mt-3 max-w-lg text-sm leading-6 muted">{e.detail}</p></div></Reveal>)}</div></div></Reveal></div></section>
  <section id="testimonials" className="section"><div className="wrap"><Reveal><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="eyebrow">05 / Kind words</p><h2 className="section-title">Good work is<br/>a team sport<span style={{color:'var(--accent)'}}>.</span></h2></div><div className="flex gap-2"><button className="surface flex h-11 w-11 items-center justify-center rounded-full" aria-label="Previous testimonial" onClick={()=>setTestimonial((testimonial+testimonials.length-1)%testimonials.length)}><ChevronLeft size={17}/></button><button className="surface flex h-11 w-11 items-center justify-center rounded-full" aria-label="Next testimonial" onClick={()=>setTestimonial((testimonial+1)%testimonials.length)}><ChevronRight size={17}/></button></div></div></Reveal>
   <AnimatePresence mode="wait"><motion.div key={testimonial} initial={{opacity:0,x:18}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-18}} transition={{duration:.3}} className="surface mt-8 grid gap-8 rounded-3xl p-7 sm:p-11 lg:grid-cols-[1fr_260px]"><div><div className="mb-6 flex gap-1" aria-label="5 out of 5 stars">{[1,2,3,4,5].map(n=><span key={n} style={{color:'var(--accent)'}}>✳</span>)}</div><blockquote className="max-w-[780px] text-2xl font-medium leading-[1.45] tracking-tight sm:text-3xl">“{current.quote}”</blockquote><div className="mt-7 flex gap-1.5">{testimonials.map((t,i)=><button key={t.initials} aria-label={`Show testimonial ${i+1}`} onClick={()=>setTestimonial(i)} className="h-1 rounded-full transition-all" style={{width:i===testimonial?30:12,background:i===testimonial?'var(--accent)':'var(--line)'}}/>)}</div></div><div className="flex items-end gap-4 border-t pt-6 lg:flex-col lg:items-start lg:justify-end lg:border-l lg:border-t-0 lg:pl-8 lg:pt-0" style={{borderColor:'var(--line)'}}><div className="flex h-14 w-14 items-center justify-center rounded-full text-sm font-black" style={{background:'color-mix(in srgb, var(--accent) 20%, var(--panel))',color:'var(--accent)'}}>{current.initials}</div><div><p className="font-bold">{current.name}</p><p className="mt-1 text-sm muted">{current.title}</p></div></div></motion.div></AnimatePresence>
  </div></section>
  <section id="contact" className="section"><div className="wrap"><div className="relative overflow-hidden rounded-[30px] border p-6 sm:p-10 lg:p-14" style={{borderColor:'var(--line)',background:'var(--panel)'}}><div className="pointer-events-none absolute -right-24 -top-28 h-80 w-80 rounded-full opacity-15 blur-[100px]" style={{background:'var(--accent)'}}/><div className="relative grid gap-12 lg:grid-cols-[.9fr_1.1fr]"><div><p className="eyebrow">06 / Your turn</p><h2 className="mt-5 text-[clamp(3rem,6vw,5.5rem)] font-black leading-[.9] tracking-[-.08em]">Have a good<br/>one in mind<span style={{color:'var(--accent)'}}>?</span></h2><p className="mt-6 max-w-md leading-7 muted">Tell me what you’re building, what feels stuck, or what you wish existed. I’ll get back to you as soon as I can.</p><a href={`mailto:${profile.email}`} className="mt-7 inline-flex items-center gap-2 text-sm font-bold" style={{color:'var(--accent)'}}>{profile.email} <ArrowUpRight size={15}/></a><div className="mt-12 flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-full border" style={{borderColor:'var(--line)'}}><span className="h-2 w-2 rounded-full" style={{background:'var(--accent)'}}/></span><div><p className="text-xs font-bold">Usually replies within 2 days</p><p className="mt-1 text-xs muted">{profile.location}</p></div></div></div>
   <form onSubmit={submit} noValidate className="relative space-y-4 rounded-2xl border p-5 sm:p-7" style={{borderColor:'var(--line)',background:'color-mix(in srgb, var(--bg) 60%, transparent)'}}><div className="grid gap-4 sm:grid-cols-2"><label className="block"><span className="mb-2 block text-xs font-bold">Your name</span><input className="form-field" placeholder="Jane Smith" autoComplete="name" value={form.name} onChange={e=>{setForm({...form,name:e.target.value});setErrors({...errors,name:''});}} aria-invalid={!!errors.name}/>{errors.name&&<span className="mt-1 block text-xs text-red-400">{errors.name}</span>}</label><label className="block"><span className="mb-2 block text-xs font-bold">Email address</span><input className="form-field" type="email" placeholder="jane@company.com" autoComplete="email" value={form.email} onChange={e=>{setForm({...form,email:e.target.value});setErrors({...errors,email:''});}} aria-invalid={!!errors.email}/>{errors.email&&<span className="mt-1 block text-xs text-red-400">{errors.email}</span>}</label></div><label className="block"><span className="mb-2 block text-xs font-bold">What are you thinking about?</span><textarea className="form-field min-h-[150px] resize-y" placeholder="A little context about your project…" value={form.message} onChange={e=>{setForm({...form,message:e.target.value});setErrors({...errors,message:''});}} aria-invalid={!!errors.message}/>{errors.message&&<span className="mt-1 block text-xs text-red-400">{errors.message}</span>}</label><div aria-live="polite">{status==='success'&&<p className="flex items-center gap-2 text-sm" style={{color:'var(--accent)'}}><Check size={16}/> Message received — thanks for reaching out!</p>}{status==='error'&&<p className="text-sm text-red-400">Something went wrong. Please try again or email me directly.</p>}</div><button type="submit" disabled={status==='sending'} className="btn btn-primary w-full disabled:cursor-wait disabled:opacity-60">{status==='sending'?'Sending message…':status==='success'?'Send another message':'Send your message'} <Send size={15}/></button><p className="text-center text-[10px] muted">Your details are only used to reply to your message.</p></form>
  </div></div></div></section>
  <footer className="border-t py-7" style={{borderColor:'var(--line)'}}><div className="wrap flex flex-col items-center justify-between gap-4 sm:flex-row"><a href="#home" className="flex items-center gap-2 text-sm font-bold"><span className="flex h-7 w-7 items-center justify-center rounded-lg text-xs font-black" style={{background:'var(--accent)',color:'#111'}}>a.</span> alexmorgan.dev</a><p className="text-xs muted">Designed with intent. Built with care. © {new Date().getFullYear()} Alex Morgan.</p><a href="#home" className="inline-flex items-center gap-2 text-xs muted hover:opacity-70">Back to top <ArrowUpRight size={13}/></a></div></footer>
 </main>
}
function Skill({name,level}:{name:string;level:number}){const ref=useRef(null);const inView=useInView(ref,{once:true});return <div ref={ref} className="mb-5 last:mb-0"><div className="mb-2 flex items-center justify-between gap-2"><span className="text-[11px]" style={{color:'var(--muted)'}}>{name}</span><span className="text-[10px]" style={{color:'var(--accent)'}}>{level}%</span></div><div className="skill-track"><motion.div className="skill-fill" initial={{scaleX:0}} animate={{scaleX:inView?level/100:0}} transition={{duration:1,ease:[.22,1,.36,1]}}/></div></div>}
